[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
remappings = [
    "forge-std/=lib/forge-std/src/",
    "solady/=lib/solady/src/",
    "solady_test/=lib/solady/test/",
    "ExcessivelySafeCall/=lib/ExcessivelySafeCall/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "I4337/=lib/account-abstraction/src/",

    # Kernel internal shortcuts
    "src/=src/",
    "src/core/=src/core/",
    "src/interfaces/=src/interfaces/",
    "src/types/=src/types/",
    "src/utils/=src/utils/"
]
