[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
remappings = [
    "forge-std/=lib/forge-std/src/",
    "solady/=lib/solady/src/",
    "solady_test/=lib/solady/test/",
    "ExcessivelySafeCall/=lib/ExcessivelySafeCall/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "I4337/=lib/account-abstraction/src/",

    # Kernel internal shortcuts
    "src/=src/",
    "src/core/=src/core/",
    "src/interfaces/=src/interfaces/",
    "src/types/=src/types/",
    "src/utils/=src/utils/"
]

# RPC endpoints
[rpc_endpoints]
og = "${RPC_URL}"

# 0G Explorer
[etherscan]
og = { key = "no-key-needed", url = "https://chainscan.0g.ai/api" }

[profile.ci]
fuzz_runs = 10000
invariant_runs = 1000

[profile.intense]
fuzz_runs = 50000
invariant_runs = 10000

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = "long"
multiline_func_header = "all"
quote_style = "double"
number_underscore = "thousands"